# Generated by Django 5.0.7 on 2024-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_enrollment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
